# Site settings
title: Zhihao Lou's note book
email: lzh1984@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Zhihao Lou's note book. Here you can find my notes about things
  I'm learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhlou.github.io" # the base hostname & protocol for your site
twitter_username: zhlou
github_username:  zhlou

# Build settings
markdown: kramdown
